### ISSUE TITLE
original spotify not working

### ISSUE THREAD

**Issue by luuuciaj** [Daksh777/SpotifyNoPremium#104]
I have uninstalled and reinstalled Spotify, deleted the Spicetify folders, and still can't use the original version of Spotify downloaded from the Microsoft Store. I can't see my playlists and I can't play music either
![Captura de pantalla 2023-07-09 005843](https://github.com/Daksh777/SpotifyNoPremium/assets/113423665/fc3dd4eb-4754-42c9-b270-c24000e6d11d)

**Comment by imloualvaro** [comment]
repo doesn't work for latest updates. only till 1.2.9.743.g85d9593d and you are using 1.2.15 probably

**Comment by Daksh777** [comment]
Apologies for the inactivity, I have been really busy lately.
The repo does work for the latest version of the app and Spicetify, I've double-checked it today and pushing an update

@luuuciaj would you mind connecting on Discord or Telegram or Google Meet so that I can see your shared screen and look for any possible fixes?

**Comment by luuuciaj** [comment]
Yes, it'd be great. Please contact me through discord. My user is queen.slayer

**Comment by Daksh777** [comment]
I've sent you a friend request!
